### ISSUE TITLE
Failed to add ruleset 

### ISSUE THREAD

**Issue by Origami-Lemon** [Artemis-chan/osu-DIVA#71] opened 2022-03-14 23:29 UTC
!
![Screenshot (109)](https://user-images.githubusercontent.com/95983152/158277250-3e660df1-d75c-46c5-be39-0e4464292389.png)

**Comment by Artemis-chan** [comment] 2022-03-15 07:34
duplicate of #38
I'll publish a new build

**Closed by Artemis-chan** 2022-03-15 07:34 UTC
Labels: closed: duplicate

**Comment by Artemis-chan** [comment] 2022-03-15 07:39
thanks @Thesola10

**Comment by Thesola10** [comment] 2022-03-15 07:41
@Artemis-chan pls update the release message as you see fit

**Comment by Artemis-chan** [comment] 2022-03-15 07:44
@Thesola10 already did 👍🏼
